// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ConectarToWiFi

#include "../ui.h"

void ui_ConnectedScreen_screen_init(void)
{
    ui_ConnectedScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ConnectedScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ConnectedPanel = lv_obj_create(ui_ConnectedScreen);
    lv_obj_set_width(ui_ConnectedPanel, lv_pct(100));
    lv_obj_set_height(ui_ConnectedPanel, lv_pct(100));
    lv_obj_set_align(ui_ConnectedPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ConnectedPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ConnectedMainPanel = lv_obj_create(ui_ConnectedPanel);
    lv_obj_set_width(ui_ConnectedMainPanel, lv_pct(106));
    lv_obj_set_height(ui_ConnectedMainPanel, lv_pct(109));
    lv_obj_set_align(ui_ConnectedMainPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ConnectedMainPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ConnectedMainPanel, lv_color_hex(0x727A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConnectedMainPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConnectedMainPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ConnectedMainPanel, 10, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_ConnectedMainPanel);
    lv_obj_set_height(ui_Panel3, 45);
    lv_obj_set_width(ui_Panel3, lv_pct(100));
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, -120);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x727A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgMainLeftButton1 = lv_imgbtn_create(ui_Panel3);
    lv_imgbtn_set_src(ui_ImgMainLeftButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_izq_032x032_png, NULL);
    lv_obj_set_width(ui_ImgMainLeftButton1, 32);
    lv_obj_set_height(ui_ImgMainLeftButton1, 32);
    lv_obj_set_x(ui_ImgMainLeftButton1, -190);
    lv_obj_set_y(ui_ImgMainLeftButton1, 0);
    lv_obj_set_align(ui_ImgMainLeftButton1, LV_ALIGN_CENTER);

    ui_ImgMainRightButton2 = lv_imgbtn_create(ui_Panel3);
    lv_imgbtn_set_src(ui_ImgMainRightButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_der_032x032_png, NULL);
    lv_obj_set_width(ui_ImgMainRightButton2, 32);
    lv_obj_set_height(ui_ImgMainRightButton2, 32);
    lv_obj_set_x(ui_ImgMainRightButton2, 190);
    lv_obj_set_y(ui_ImgMainRightButton2, 0);
    lv_obj_set_align(ui_ImgMainRightButton2, LV_ALIGN_CENTER);

    ui_Panel4 = lv_obj_create(ui_ConnectedMainPanel);
    lv_obj_set_height(ui_Panel4, 240);
    lv_obj_set_width(ui_Panel4, lv_pct(100));
    lv_obj_set_x(ui_Panel4, 0);
    lv_obj_set_y(ui_Panel4, 30);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x727A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SSIDLabel = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_SSIDLabel, 145);
    lv_obj_set_height(ui_SSIDLabel, 35);
    lv_obj_set_x(ui_SSIDLabel, -135);
    lv_obj_set_y(ui_SSIDLabel, lv_pct(-36));
    lv_obj_set_align(ui_SSIDLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SSIDLabel, "Conectado a la Red WiFi (SSID).:");

    ui_WiFiSSIDLabel = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_WiFiSSIDLabel, 260);
    lv_obj_set_height(ui_WiFiSSIDLabel, 15);
    lv_obj_set_x(ui_WiFiSSIDLabel, 80);
    lv_obj_set_y(ui_WiFiSSIDLabel, lv_pct(-40));
    lv_obj_set_align(ui_WiFiSSIDLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFiSSIDLabel, "SSID");

    ui_LocalIPLabel = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_LocalIPLabel, 145);
    lv_obj_set_height(ui_LocalIPLabel, 15);
    lv_obj_set_x(ui_LocalIPLabel, -135);
    lv_obj_set_y(ui_LocalIPLabel, lv_pct(-12));
    lv_obj_set_align(ui_LocalIPLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LocalIPLabel, "Direccion IP.:");

    ui_WiFiLocalIPLabel = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_WiFiLocalIPLabel, 260);
    lv_obj_set_height(ui_WiFiLocalIPLabel, 15);
    lv_obj_set_x(ui_WiFiLocalIPLabel, 80);
    lv_obj_set_y(ui_WiFiLocalIPLabel, lv_pct(-12));
    lv_obj_set_align(ui_WiFiLocalIPLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFiLocalIPLabel, "xx.xx.xx.xx");

    ui_dnsIPLabel = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_dnsIPLabel, 145);
    lv_obj_set_height(ui_dnsIPLabel, 15);
    lv_obj_set_x(ui_dnsIPLabel, -135);
    lv_obj_set_y(ui_dnsIPLabel, lv_pct(12));
    lv_obj_set_align(ui_dnsIPLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dnsIPLabel, "Direccion DNS.:");

    ui_WiFidnsIPLabel = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_WiFidnsIPLabel, 260);
    lv_obj_set_height(ui_WiFidnsIPLabel, 15);
    lv_obj_set_x(ui_WiFidnsIPLabel, 80);
    lv_obj_set_y(ui_WiFidnsIPLabel, lv_pct(12));
    lv_obj_set_align(ui_WiFidnsIPLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFidnsIPLabel, "xx.xx.xx.xx");

    ui_macAddressLabel = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_macAddressLabel, 145);
    lv_obj_set_height(ui_macAddressLabel, 15);
    lv_obj_set_x(ui_macAddressLabel, -135);
    lv_obj_set_y(ui_macAddressLabel, lv_pct(36));
    lv_obj_set_align(ui_macAddressLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_macAddressLabel, "Direccion MAC.:");

    ui_WiFimacAddressLabel = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_WiFimacAddressLabel, 260);
    lv_obj_set_height(ui_WiFimacAddressLabel, 15);
    lv_obj_set_x(ui_WiFimacAddressLabel, 80);
    lv_obj_set_y(ui_WiFimacAddressLabel, lv_pct(36));
    lv_obj_set_align(ui_WiFimacAddressLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFimacAddressLabel, "xx:xx:xx:xx:xx:xx:xx");

    lv_obj_add_event_cb(ui_ImgMainLeftButton1, ui_event_ImgMainLeftButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgMainRightButton2, ui_event_ImgMainRightButton2, LV_EVENT_ALL, NULL);

}
