// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ConectarToWiFi

#include "../ui.h"

void ui_InitScreen_screen_init(void)
{
    ui_InitScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_InitScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_InitPanel = lv_obj_create(ui_InitScreen);
    lv_obj_set_width(ui_InitPanel, lv_pct(100));
    lv_obj_set_height(ui_InitPanel, lv_pct(100));
    lv_obj_set_align(ui_InitPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_InitPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_InitPanel, &ui_img_burbujas_160x160_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_InitPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_InitPanel, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InitPanel2 = lv_obj_create(ui_InitPanel);
    lv_obj_set_height(ui_InitPanel2, 55);
    lv_obj_set_width(ui_InitPanel2, lv_pct(72));
    lv_obj_set_x(ui_InitPanel2, 0);
    lv_obj_set_y(ui_InitPanel2, -120);
    lv_obj_set_align(ui_InitPanel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_InitPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_InitPanel2, lv_color_hex(0x727A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_InitPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_InitPanel2);
    lv_obj_set_width(ui_Label1, lv_pct(100));
    lv_obj_set_height(ui_Label1, lv_pct(170));
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "ERNESTO JOSE GUERRERO GONZALEZ\nAIoT Transitorios Hidraulicos");
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoG2EJImage = lv_img_create(ui_InitPanel);
    lv_img_set_src(ui_LogoG2EJImage, &ui_img_logo_g2ej_105x156_png);
    lv_obj_set_width(ui_LogoG2EJImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LogoG2EJImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LogoG2EJImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LogoG2EJImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LogoG2EJImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_udFJdCImage = lv_img_create(ui_InitPanel);
    lv_img_set_src(ui_udFJdCImage, &ui_img_logo_ud_fjdc_058x090_png);
    lv_obj_set_width(ui_udFJdCImage, 58);
    lv_obj_set_height(ui_udFJdCImage, 90);
    lv_obj_set_x(ui_udFJdCImage, -200);
    lv_obj_set_y(ui_udFJdCImage, -112);
    lv_obj_set_align(ui_udFJdCImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_udFJdCImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_udFJdCImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgInitRightButton = lv_imgbtn_create(ui_InitPanel);
    lv_imgbtn_set_src(ui_ImgInitRightButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_der_032x032_png, NULL);
    lv_obj_set_width(ui_ImgInitRightButton, 32);
    lv_obj_set_height(ui_ImgInitRightButton, 32);
    lv_obj_set_x(ui_ImgInitRightButton, 202);
    lv_obj_set_y(ui_ImgInitRightButton, -120);
    lv_obj_set_align(ui_ImgInitRightButton, LV_ALIGN_CENTER);

    ui_FotoG2EJImage = lv_img_create(ui_InitPanel);
    lv_img_set_src(ui_FotoG2EJImage, &ui_img_foto_g2ej_064x064_png);
    lv_obj_set_width(ui_FotoG2EJImage, 64);
    lv_obj_set_height(ui_FotoG2EJImage, 64);
    lv_obj_set_x(ui_FotoG2EJImage, -193);
    lv_obj_set_y(ui_FotoG2EJImage, 115);
    lv_obj_set_align(ui_FotoG2EJImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FotoG2EJImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_FotoG2EJImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIoTImage = lv_img_create(ui_InitPanel);
    lv_img_set_src(ui_AIoTImage, &ui_img_logo_aiot_157x105_png);
    lv_obj_set_width(ui_AIoTImage, 157);
    lv_obj_set_height(ui_AIoTImage, 105);
    lv_obj_set_x(ui_AIoTImage, 154);
    lv_obj_set_y(ui_AIoTImage, 108);
    lv_obj_set_align(ui_AIoTImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIoTImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIoTImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ImgInitRightButton, ui_event_ImgInitRightButton, LV_EVENT_ALL, NULL);

}
