// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ConectarToWiFi

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainPanel = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_MainPanel, lv_pct(100));
    lv_obj_set_height(ui_MainPanel, lv_pct(100));
    lv_obj_set_align(ui_MainPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainTabView = lv_tabview_create(ui_MainPanel, LV_DIR_TOP, 25);
    lv_obj_set_width(ui_MainTabView, lv_pct(106));
    lv_obj_set_height(ui_MainTabView, lv_pct(109));
    lv_obj_set_align(ui_MainTabView, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainTabView, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainTabView, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MainTabView, lv_color_hex(0x727A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MainTabView, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainTabView, 2, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_TabPage1 = lv_tabview_add_tab(ui_MainTabView, "Connec To WiFi");

    ui_PanelCaneectRescan = lv_obj_create(ui_TabPage1);
    lv_obj_set_height(ui_PanelCaneectRescan, 45);
    lv_obj_set_width(ui_PanelCaneectRescan, lv_pct(100));
    lv_obj_set_x(ui_PanelCaneectRescan, 0);
    lv_obj_set_y(ui_PanelCaneectRescan, -116);
    lv_obj_set_align(ui_PanelCaneectRescan, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelCaneectRescan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelCaneectRescan, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelCaneectRescan, lv_color_hex(0x727A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCaneectRescan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConnectButton = lv_btn_create(ui_PanelCaneectRescan);
    lv_obj_set_width(ui_ConnectButton, 100);
    lv_obj_set_height(ui_ConnectButton, 35);
    lv_obj_set_x(ui_ConnectButton, -100);
    lv_obj_set_y(ui_ConnectButton, 0);
    lv_obj_set_align(ui_ConnectButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConnectButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConnectButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ConnectLabel = lv_label_create(ui_ConnectButton);
    lv_obj_set_width(ui_ConnectLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConnectLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConnectLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConnectLabel, "Connect");

    ui_RescanButton = lv_btn_create(ui_PanelCaneectRescan);
    lv_obj_set_width(ui_RescanButton, 100);
    lv_obj_set_height(ui_RescanButton, 35);
    lv_obj_set_x(ui_RescanButton, 100);
    lv_obj_set_y(ui_RescanButton, 0);
    lv_obj_set_align(ui_RescanButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RescanButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RescanButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RescanLabel = lv_label_create(ui_RescanButton);
    lv_obj_set_width(ui_RescanLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RescanLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RescanLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RescanLabel, "Re-Scan");

    ui_ImgMainLeftButton = lv_imgbtn_create(ui_PanelCaneectRescan);
    lv_imgbtn_set_src(ui_ImgMainLeftButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_izq_032x032_png, NULL);
    lv_obj_set_width(ui_ImgMainLeftButton, 32);
    lv_obj_set_height(ui_ImgMainLeftButton, 32);
    lv_obj_set_x(ui_ImgMainLeftButton, -190);
    lv_obj_set_y(ui_ImgMainLeftButton, 0);
    lv_obj_set_align(ui_ImgMainLeftButton, LV_ALIGN_CENTER);

    ui_ImgButton2 = lv_imgbtn_create(ui_PanelCaneectRescan);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_der_032x032_png, NULL);
    lv_obj_set_width(ui_ImgButton2, 32);
    lv_obj_set_height(ui_ImgButton2, 32);
    lv_obj_set_x(ui_ImgButton2, 190);
    lv_obj_set_y(ui_ImgButton2, 0);
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_CENTER);

    ui_DropDownSSID = lv_dropdown_create(ui_TabPage1);
    lv_dropdown_set_options(ui_DropDownSSID, "");
    lv_obj_set_width(ui_DropDownSSID, 325);
    lv_obj_set_height(ui_DropDownSSID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropDownSSID, 50);
    lv_obj_set_y(ui_DropDownSSID, -70);
    lv_obj_set_align(ui_DropDownSSID, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropDownSSID, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_TextAreaPassword = lv_textarea_create(ui_TabPage1);
    lv_obj_set_width(ui_TextAreaPassword, 325);
    lv_obj_set_height(ui_TextAreaPassword, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_TextAreaPassword, 50);
    lv_obj_set_y(ui_TextAreaPassword, -30);
    lv_obj_set_align(ui_TextAreaPassword, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextAreaPassword, 128);
    lv_textarea_set_placeholder_text(ui_TextAreaPassword, "Enter Password");
    lv_textarea_set_password_mode(ui_TextAreaPassword, true);



    ui_Label3 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label3, 120);
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -165);
    lv_obj_set_y(ui_Label3, -70);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "WiFi SSID");

    ui_Label4 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label4, 120);
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -165);
    lv_obj_set_y(ui_Label4, -30);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "WiFi Password");

    ui_Keyboard = lv_keyboard_create(ui_TabPage1);
    lv_obj_set_width(ui_Keyboard, lv_pct(100));
    lv_obj_set_height(ui_Keyboard, lv_pct(60));
    lv_obj_set_x(ui_Keyboard, 0);
    lv_obj_set_y(ui_Keyboard, 65);
    lv_obj_set_align(ui_Keyboard, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Keyboard, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Keyboard, lv_color_hex(0x727A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Keyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage2 = lv_tabview_add_tab(ui_MainTabView, "AIoT Transitorios Hidraulicos");

    ui_ConnectingLabel = lv_label_create(ui_MainPanel);
    lv_obj_set_width(ui_ConnectingLabel, lv_pct(40));
    lv_obj_set_height(ui_ConnectingLabel, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_align(ui_ConnectingLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConnectingLabel, "Connecting.............");
    lv_obj_add_flag(ui_ConnectingLabel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_ConnectingLabel, lv_color_hex(0xE10E0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConnectingLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ConnectButton, ui_event_ConnectButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RescanButton, ui_event_RescanButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgMainLeftButton, ui_event_ImgMainLeftButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton2, ui_event_ImgButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaPassword, ui_event_TextAreaPassword, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard, ui_TextAreaPassword);

}
