// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ConectarToWiFi

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_InitScreen
void ui_InitScreen_screen_init(void);
lv_obj_t * ui_InitScreen;
lv_obj_t * ui_InitPanel;
lv_obj_t * ui_InitPanel2;
lv_obj_t * ui_Label1;
lv_obj_t * ui_LogoG2EJImage;
lv_obj_t * ui_udFJdCImage;
void ui_event_ImgInitRightButton(lv_event_t * e);
lv_obj_t * ui_ImgInitRightButton;
lv_obj_t * ui_FotoG2EJImage;
lv_obj_t * ui_AIoTImage;


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_MainPanel;
lv_obj_t * ui_MainTabView;
lv_obj_t * ui_TabPage1;
lv_obj_t * ui_PanelCaneectRescan;
void ui_event_ConnectButton(lv_event_t * e);
lv_obj_t * ui_ConnectButton;
lv_obj_t * ui_ConnectLabel;
void ui_event_RescanButton(lv_event_t * e);
lv_obj_t * ui_RescanButton;
lv_obj_t * ui_RescanLabel;
void ui_event_ImgMainLeftButton(lv_event_t * e);
lv_obj_t * ui_ImgMainLeftButton;
void ui_event_ImgButton2(lv_event_t * e);
lv_obj_t * ui_ImgButton2;
lv_obj_t * ui_DropDownSSID;
void ui_event_TextAreaPassword(lv_event_t * e);
lv_obj_t * ui_TextAreaPassword;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Keyboard;
lv_obj_t * ui_TabPage2;
lv_obj_t * ui_ConnectingLabel;


// SCREEN: ui_ConnectedScreen
void ui_ConnectedScreen_screen_init(void);
lv_obj_t * ui_ConnectedScreen;
lv_obj_t * ui_ConnectedPanel;
lv_obj_t * ui_ConnectedMainPanel;
lv_obj_t * ui_Panel3;
void ui_event_ImgMainLeftButton1(lv_event_t * e);
lv_obj_t * ui_ImgMainLeftButton1;
void ui_event_ImgMainRightButton2(lv_event_t * e);
lv_obj_t * ui_ImgMainRightButton2;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_SSIDLabel;
lv_obj_t * ui_WiFiSSIDLabel;
lv_obj_t * ui_LocalIPLabel;
lv_obj_t * ui_WiFiLocalIPLabel;
lv_obj_t * ui_dnsIPLabel;
lv_obj_t * ui_WiFidnsIPLabel;
lv_obj_t * ui_macAddressLabel;
lv_obj_t * ui_WiFimacAddressLabel;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_burbujas_x[1] = {&ui_img_burbujas_160x160_png};
const lv_img_dsc_t * ui_imgset_der_x[1] = {&ui_img_der_032x032_png};
const lv_img_dsc_t * ui_imgset_foto_g2ej_x[1] = {&ui_img_foto_g2ej_064x064_png};
const lv_img_dsc_t * ui_imgset_izq_x[1] = {&ui_img_izq_032x032_png};
const lv_img_dsc_t * ui_imgset_logo_aiot_157x[1] = {&ui_img_logo_aiot_157x105_png};
const lv_img_dsc_t * ui_imgset_logo_g2ej_105x[1] = {&ui_img_logo_g2ej_105x156_png};
const lv_img_dsc_t * ui_imgset_logo_ud_fjdc_058x[1] = {&ui_img_logo_ud_fjdc_058x090_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ImgInitRightButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_ConnectButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ConnectToRouter(e);
    }
}
void ui_event_RescanButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ReScanWiFiSSID(e);
    }
}
void ui_event_ImgMainLeftButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_InitScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_InitScreen_screen_init);
    }
}
void ui_event_ImgButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ConnectedScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ConnectedScreen_screen_init);
    }
}
void ui_event_TextAreaPassword(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        ShowKeyBoard(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        HideKeyBoard(e);
    }
    if(event_code == LV_EVENT_READY) {
        HideKeyBoard(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        ShowKeyBoard(e);
    }
}
void ui_event_ImgMainLeftButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_ImgMainRightButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_InitScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_InitScreen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_InitScreen_screen_init();
    ui_MainScreen_screen_init();
    ui_ConnectedScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_InitScreen);
}
