// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ConectarToWiFi

#ifndef _CONECTARTOWIFI_UI_H
#define _CONECTARTOWIFI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_InitScreen
void ui_InitScreen_screen_init(void);
extern lv_obj_t * ui_InitScreen;
extern lv_obj_t * ui_InitPanel;
extern lv_obj_t * ui_InitPanel2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_LogoG2EJImage;
extern lv_obj_t * ui_udFJdCImage;
void ui_event_ImgInitRightButton(lv_event_t * e);
extern lv_obj_t * ui_ImgInitRightButton;
extern lv_obj_t * ui_FotoG2EJImage;
extern lv_obj_t * ui_AIoTImage;
// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_MainPanel;
extern lv_obj_t * ui_MainTabView;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_PanelCaneectRescan;
void ui_event_ConnectButton(lv_event_t * e);
extern lv_obj_t * ui_ConnectButton;
extern lv_obj_t * ui_ConnectLabel;
void ui_event_RescanButton(lv_event_t * e);
extern lv_obj_t * ui_RescanButton;
extern lv_obj_t * ui_RescanLabel;
void ui_event_ImgMainLeftButton(lv_event_t * e);
extern lv_obj_t * ui_ImgMainLeftButton;
void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_DropDownSSID;
void ui_event_TextAreaPassword(lv_event_t * e);
extern lv_obj_t * ui_TextAreaPassword;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Keyboard;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_ConnectingLabel;
// SCREEN: ui_ConnectedScreen
void ui_ConnectedScreen_screen_init(void);
extern lv_obj_t * ui_ConnectedScreen;
extern lv_obj_t * ui_ConnectedPanel;
extern lv_obj_t * ui_ConnectedMainPanel;
extern lv_obj_t * ui_Panel3;
void ui_event_ImgMainLeftButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgMainLeftButton1;
void ui_event_ImgMainRightButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgMainRightButton2;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_SSIDLabel;
extern lv_obj_t * ui_WiFiSSIDLabel;
extern lv_obj_t * ui_LocalIPLabel;
extern lv_obj_t * ui_WiFiLocalIPLabel;
extern lv_obj_t * ui_dnsIPLabel;
extern lv_obj_t * ui_WiFidnsIPLabel;
extern lv_obj_t * ui_macAddressLabel;
extern lv_obj_t * ui_WiFimacAddressLabel;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_burbujas_160x160_png);    // assets\Burbujas_160x160.png
LV_IMG_DECLARE(ui_img_logo_g2ej_105x156_png);    // assets\Logo_G2EJ_105x156.png
LV_IMG_DECLARE(ui_img_logo_ud_fjdc_058x090_png);    // assets\Logo_ud_FJdC_058x090.png
LV_IMG_DECLARE(ui_img_der_032x032_png);    // assets\Der_032x032.png
LV_IMG_DECLARE(ui_img_foto_g2ej_064x064_png);    // assets\Foto_G2EJ_064x064.png
LV_IMG_DECLARE(ui_img_logo_aiot_157x105_png);    // assets\Logo_AIoT_157x105.png
LV_IMG_DECLARE(ui_img_izq_032x032_png);    // assets\Izq_032x032.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
